### ISSUE TITLE
Code signing broken with 10.10 Yosemite

### ISSUE THREAD

**Issue by JonasNielsen** [webcracy/motion-sparkle#9]
Signing the app with codesign appear to be broken with 10.10 Yosemite. 

Here's the full output:

```
Codesign ./build/MacOSX-10.9-Release/Screenmailer.app
./build/MacOSX-10.9-Release/Screenmailer.app: bundle format is ambiguous (could be app or framework)
In subcomponent: /Users/jonas/OSXApps/motion-screenemailer/build/MacOSX-10.9-Release/Screenmailer.app/Contents/Frameworks/Sparkle.framework
rake aborted!
Command failed with status (1): [/usr/bin/codesign --deep --force --sign "D...]
/Users/jonas/.rvm/gems/ruby-2.1.2@motion-screenmailer/gems/motion-sparkle-0.0.5/lib/motion/project/project.rb:43:in `codesign'
/Library/RubyMotion/lib/motion/project/app.rb:86:in `codesign'
/Library/RubyMotion/lib/motion/project/template/osx.rb:49:in `block (2 levels) in <top (required)>'
/Users/jonas/.rvm/gems/ruby-2.1.2@motion-screenmailer/bin/ruby_executable_hooks:15:in `eval'
/Users/jonas/.rvm/gems/ruby-2.1.2@motion-screenmailer/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => build:release
(See full trace by running task with --trace)
```

Any ideas how to fix this?

Setup:
motion-sparkle 0.0.5
RubyMotion 2.34
OS X 10.10
Xcode 6.1 beta

**Comment by nickyhajal** [comment]
Hey guys, I am seeing this issue again with RubyMotion 3.3.

rake build:release fails to correctly sign my app when it has motion-sparkle with the same "bundle format is ambiguous (could be app or framework)" error. 

Even manually signing App/Contents/Frameworks/Sparkle.framework/Versions/A and Versions/Current doesn't create a valid app.

It had been working fine before.

Are you seeing similar issues or is it something on my end?

Thanks!

**Comment by webcracy** [comment]
@nickyhajal If you haven't, please try to use the `master` branch and lemme know if this works for you.

    #Gemfile
    gem 'motion-sparkle', github: 'webcracy/motion-sparkle'

**Comment by nickyhajal** [comment]
@webcracy Ah, yes I was still on the yosemite-hacks branch. That worked, thank you!
